server:
  port: ${PORT:8081}
spring:
  devtools:
    livereload:
      enable: true
  datasource:
    hikari:
      connection_timeout: 10000
      maximum_pool_size: 5
    url: jdbc:postgresql://ec2-18-211-97-89.compute-1.amazonaws.com:5432/d8q0o5fiv0e4f6?sslmode=require&user=wutaqzfnqsaomd&password=a143f3196df8089ba58e71a76674887cac9948f0f3c903d546a901a03f22e852
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      jdbc:
        non_contextual_creation: true

