server:
  port: ${PORT:8081}
spring:
  devtools:
    livereload:
      enable: true
  datasource:
    hikari:
      connection_timeout: 10000
      maximum_pool_size: 5
    url: jdbc:postgresql://ec2-54-225-190-241.compute-1.amazonaws.com:5432/d48hut4gjd1v0b?sslmode=require&user=gyldslkdthmwmz&password=966c9d2b1d8c1497f822fd1cc2eb0751f9960c26740c3ee454ad26604cf5ee6b
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      jdbc:
        non_contextual_creation: true

